name: minipmdb

services:
  mongodb:
    image: mongo:8.2.6-noble
    restart: unless-stopped
    command: ["mongod", "--bind_ip_all"]
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - minipmdb-mongodb:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand({ ping: 1 })"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

volumes:
  minipmdb-mongodb:
